server:
  port: ${PORT_TO_EXPOSE:8081}

spring:
  flyway:
    enabled: false
#    thymeleaf:
##      prefix:
#        classpath:  /templates/
#        suffix:   html
 # main:
 #   web-application-type:
  application:
    name: bozhko_project
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  hibernate:
    ddl-auto: update
    show_sql: true
    format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/test?currentSchema=public
    url: jdbc:postgresql://localhost/test
    username: user
    password: 12345

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    security:
      - basicAuth: []
    paths:
      /something:
        get:
          security:
            - basicAuth: []

#paths:
#  /users:
#    get:
#      summary:
#      description:
#      responses:
#        '200':    # status code
#          description:
#          content:
#            application/json:
#              schema:
#                type: array
#                items:
#                  type: string

  #jpa.hibernate.ddl-auto: update
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
springfox:
  documentation:
    swagger:
      v2:
        path: /v3/api-docs



  #spring.jpa.properties.hibernate.format_sql=false
  #spring.jpa.generate-ddl=false
  #spring.jpa.hibernate.ddl-auto=none
  #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
  
  # Fix Postgres JPA Error (Method org.postgresql.jdbc.PgConnection.createClob()).
  #spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


