CREATE TABLE announcement (
  id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_id smallint,
   product_id smallint,
   CONSTRAINT pk_announcement PRIMARY KEY (id),
   title VARCHAR(255) NOT NULL
);

ALTER TABLE announcement ADD CONSTRAINT FK_ANNOUNCEMENT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE announcement ADD CONSTRAINT FK_ANNOUNCEMENT_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

